return {}
-- return {
--   {
--     "nvimtools/none-ls.nvim",
--     opts = function(_, opts)
--       local null_ls = require("null-ls")
--       opts.sources = opts.sources or {}
--       table.insert(
--         opts.sources,
--         null_ls.builtins.diagnostics.ktlint.with({
--           diagnostics_postprocess = function(diagnostic)
--             if diagnostic.severity == vim.diagnostic.severity.WARN then
--               diagnostic.message = nil -- Suppress warnings
--             end
--           end,
--         })
--       )
--     end,
--   },
-- }
