return {}

-- local cmp = require("cmp")
-- return {
--   "hrsh7th/nvim-cmp",
--   opts = {
--     completion = {
--       completeopt = "menu,menuone,noinsert,noselect",
--     },
--     mapping = {
--       ["<CR>"] = cmp.mapping(function(fallback)
--         cmp.confirm({ select = false })
--         fallback()
--       end),
--       ["<S-Tab>"] = cmp.mapping(function(fallback)
--         cmp.confirm({ select = false })
--         fallback()
--       end),
--       ["<Tab>"] = cmp.mapping(function(fallback)
--         -- This little snippet will confirm with tab, and if no entry is selected, will confirm the first item
--         if cmp.visible() then
--           local entry = cmp.get_selected_entry()
--           if not entry then
--             cmp.confirm({ select = false })
--             fallback()
--             -- cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
--           else
--             cmp.confirm({ select = true })
--           end
--         else
--           fallback()
--         end
--       end, { "i", "s", "c" }),
--     },
--   },
-- }
