"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Doğaç Eldenk"
email = "dogacel@gmail.com"

[ui]
default-command = "st"
pager = "delta"
diff-format = "git"

[delta]
side-by-side = true
line-numbers = true
theme = "Monokai Extended"

[git]
private-commits = '''description(glob:'private:*')'''
